=== bvhest/Pikachu_Analysis/webapp.b2c/cmc2/xml/doctype_attributes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="doctypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="doctype" type="type-doctype" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="DocTimeStamp" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="type-doctype">
    <xs:attribute name="code" type="type-assettype"/>
    <xs:attribute name="master" type="type-assettype" use="optional"/>
    <xs:attribute name="suffix" type="type-suffix" use="required"/>
    <xs:attribute name="language" type="type-language" use="optional"/>
    <xs:attribute name="description" type="type-description" use="optional"/>
    <xs:attribute name="Scene7" type="type-yesno" use="optional"/>
    <xs:attribute name="Scene7Lighting" type="type-yesno" use="optional"/>
    <xs:attribute name="Scene7Videos" type="type-yesno" use="optional"/>
    <xs:attribute name="secureURL" type="type-yesno" use="optional"/>
    <xs:attribute name="S7URL" type="type-yesno" use="optional"/>
    <xs:attribute name="S7Content" type="type-yesno" use="optional"/>
    <xs:attribute name="FSS" type="type-yesno" use="optional"/>
    <xs:attribute name="FSSAssets" type="type-yesno" use="optional"/>
    <xs:attribute name="ATG" type="type-yesno" use="optional"/>
    <xs:attribute name="CQ5" type="type-yesno" use="optional"/>
    <xs:attribute name="ATGAssets" type="type-yesno" use="optional"/>
    <xs:attribute name="ATG_PCT" type="type-yesno" use="optional"/>
    <xs:attribute name="AtgLightingProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="AtgLightingFamilies" type="type-yesno" use="optional"/>    
    <xs:attribute name="LightingProducts2CQ" type="type-yesno" use="optional"/>
    <xs:attribute name="Families2CQ" type="type-yesno" use="optional"/>    
    <xs:attribute name="SefairaProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="LightingRendering" type="type-yesno" use="optional"/>
    <xs:attribute name="BrightcoveAssets" type="type-yesno" use="optional"/>
    <xs:attribute name="FlixMediaAssets" type="type-yesno" use="optional"/>
    <xs:attribute name="FlixMediaProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="EtailDetailProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="CliplisterProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="StdBroker" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL1" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL2" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL3" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL4" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL5" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL3Assets" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL4Assets" type="type-yesno" use="optional"/>
    <xs:attribute name="SyndicationL5Assets" type="type-yesno" use="optional"/>
    <xs:attribute name="ZPI" type="type-yesno" use="optional"/>
    <xs:attribute name="ZPD" type="type-yesno" use="optional"/>
    <xs:attribute name="ZAI" type="type-yesno" use="optional"/>
    <xs:attribute name="ValueCampaign" type="type-yesno" use="optional"/>
    <xs:attribute name="Thumbnail" type="type-assettype" use="optional"/>
    <xs:attribute name="Preview" type="type-assettype" use="optional"/>
    <xs:attribute name="Medium" type="type-assettype" use="optional"/>
    <xs:attribute name="ICEcat" type="type-assettype" use="optional"/> 
    <xs:attribute name="IceCatRichContent" type="type-assettype" use="optional"/>
    <xs:attribute name="WebcollageProducts" type="type-assettype" use="optional"/>
    <xs:attribute name="WebcollageAssets" type="type-assettype" use="optional"/>
    <xs:attribute name="XCProducts" type="type-yesno" use="optional"/>
    <xs:attribute name="ETLProducts" type="type-yesno" use="optional"/>
	<xs:attribute name="AutomotiveProductsExport" type="type-yesno" use="optional"/>
	<xs:attribute name="MMDProductExport" type="type-yesno" use="optional"/>
    </xs:complexType>
  
  <xs:simpleType name="type-assettype">
    <xs:restriction base="xs:string">
      <xs:length value="3"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="type-yesno">
    <xs:restriction base="xs:string">
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="type-suffix">
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-z0-9]+(,[a-z0-9]+)*)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="type-language">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="type-description">
    <xs:restriction base="xs:string">
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/ProductExport/xsl/SPAF/doctype_attributes1.xml
<?xml version='1.0' encoding='UTF-8'?>
<doctypes DocTimeStamp='2015-03-12T13:24:08' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='doctype_attributes.xsd'>
	<images>
		<doctype code='_FP' suffix='jpg' />
		<doctype code='A1P' suffix='jpg' />
		<doctype code='A2P' suffix='jpg' />
		<doctype code='A3P' suffix='jpg' />
		<doctype code='A4P' suffix='jpg' />
		<doctype code='A5P' suffix='jpg' />
		<doctype code='ABP' suffix='jpg' />
		<doctype code='APP' suffix='jpg' />
		<doctype code='BPP' suffix='jpg' />
		<doctype code='BRP' suffix='jpg' />
		<doctype code='CLL' suffix='jpg' />
		<doctype code='CLP' suffix='jpg' />
		<doctype code='CO_' suffix='jpg' />
		<doctype code='COP' suffix='jpg' />
		<doctype code='D1P' suffix='jpg' />
		<doctype code='D2P' suffix='jpg' />
		<doctype code='D3P' suffix='jpg' />
		<doctype code='D4P' suffix='jpg' />
		<doctype code='D5P' suffix='jpg' />
		<doctype code='DPP' suffix='jpg' />
		<doctype code='E1P' suffix='jpg' />
		<doctype code='E2P' suffix='jpg' />
		<doctype code='E3P' suffix='jpg' />
		<doctype code='E4P' suffix='jpg' />
		<doctype code='EL1' suffix='eps,jpeg,jpg,tif,tiff' />
		<doctype code='ENL' suffix='png' />
		<doctype code='ENR' suffix='eps,png' />
		<doctype code='FDB' suffix='jpg' />
		<doctype code='FIL' suffix='jpg' />
		<doctype code='FLP' suffix='jpg' />
		<doctype code='FMB' suffix='jpg' />
		<doctype code='FMN' suffix='tif' />
		<doctype code='FTP' suffix='jpg' />
		<doctype code='GAP' suffix='jpg' />
		<doctype code='KA1' suffix='png' />
		<doctype code='KA2' suffix='png' />
		<doctype code='KA3' suffix='tif' />
		<doctype code='KA4' suffix='tif' />
		<doctype code='KA5' suffix='tif' />
		<doctype code='KA6' suffix='tif' />
		<doctype code='KA7' suffix='tif' />
		<doctype code='KA8' suffix='tif' />
		<doctype code='KA9' suffix='tif' />
		<doctype code='L1P' suffix='jpg' />
		<doctype code='L2P' suffix='jpg' />
		<doctype code='L3P' suffix='jpg' />
		<doctype code='L4P' suffix='jpg' />
		<doctype code='MCP' suffix='jpg' />
		<doctype code='MI1' suffix='jpg' />
		<doctype code='P3D' suffix='zip' />
		<doctype code='P3X' suffix='js' />
		<doctype code='PA1' suffix='jpg' />
		<doctype code='PAH' suffix='jpg' />
		<doctype code='PBP' suffix='' />
		<doctype code='PDB' suffix='tiff,tif,jpg,eps' />
		<doctype code='PFR' suffix='tif,jpg' />
		<doctype code='PID' suffix='jpg' />
		<doctype code='PLP' suffix='jpg' />
		<doctype code='PMB' suffix='jpg' />
		<doctype code='PP2' suffix='jpg' />
		<doctype code='PS2' suffix='jpg' />
		<doctype code='PSC' suffix='jpg' />
		<doctype code='PSP' suffix='jpg' />
		<doctype code='PVP' suffix='jpg' />
		<doctype code='PWL' suffix='jpg' />
		<doctype code='R1P' suffix='jpg' />
		<doctype code='RCP' suffix='jpg' />
		<doctype code='RTP' suffix='jpg' />
		<doctype code='SLP' suffix='jpg' />
		<doctype code='TLP' suffix='jpg' />
		<doctype code='TRP' suffix='jpg' />
		<doctype code='TSL' suffix='jpg' />
		<doctype code='U1P' suffix='jpg' />
		<doctype code='U2P' suffix='jpg' />
		<doctype code='U3P' suffix='jpg' />
		<doctype code='U4P' suffix='jpg' />
		<doctype code='U5P' suffix='jpg' />
		<doctype code='UPL' suffix='jpg' />
		<doctype code='UWL' suffix='jpg' />
		<doctype code='VIM' suffix='jpg' />
		<doctype code='VS1' suffix='jpg' />
		<doctype code='VS2' suffix='jpg' />
		<doctype code='VS3' suffix='jpg' />
		<doctype code='VS4' suffix='jpg' />
		<doctype code='VS5' suffix='jpg' />
		<doctype code='PRF' suffix='pdf' />
		<doctype code='EEL' suffix='pdf' />
		<doctype code='ELR' suffix='pdf' />
		<doctype code='TEG' suffix='pdf' />
		<doctype code='P3F' suffix='jpg' />
	</images>
	<videos>
		<doctype code='HQ1' suffix='mp4' />
		<doctype code='HQ2' suffix='mp4' />
		<doctype code='HQ3' suffix='mp4' />
		<doctype code='HQ4' suffix='mp4' />
		<doctype code='HQ5' suffix='mp4' />
		<doctype code='PM2' suffix='flv' />
		<doctype code='PM3' suffix='flv' />
		<doctype code='PM4' suffix='flv' />
		<doctype code='PM5' suffix='flv' />
		<doctype code='PRD' suffix='flv' />
		<doctype code='FML' suffix='flv' />
		<doctype code='FQL' suffix='mp4' />
		<doctype code='FV1' suffix='mp4' />
		<doctype code='FV2' suffix='mp4' />
		<doctype code='FV3' suffix='mp4' />
		<doctype code='FV4' suffix='mp4' />
		<doctype code='FV5' suffix='mp4' />
		<doctype code='PRM' suffix='flv' />
	</videos>
</doctypes>
