=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_file_locale.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="static_text">
		<xs:complexType>
			<xs:sequence>
				<xs:any namespace="http://www.relate4u.com/xsl/documentation" processContents="skip"/>
				<xs:element ref="fields"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="field"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType mixed="true">
			<xs:choice>
				<xs:group maxOccurs="unbounded" minOccurs="0" ref="markup"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:NCName" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- inline markup elements -->
	<xs:group name="markup">
		<xs:choice>
			<xs:element ref="b"/>
			<xs:element ref="br"/>
		</xs:choice>
	</xs:group>
	<xs:element name="br"/>
	<xs:element name="b">
		<xs:complexType mixed="true"/>
	</xs:element>
</xs:schema>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_tr_TR.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>tr_TR</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Bilgi değişimi</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Tüm hakları saklıdır.<br/>
<br/>
Teknik özellikler önceden bildirilmeksizin değiştirilebilir. Ticari markalar Koninklijke Philips Electronics N.V. veya ilgili sahiplerine aittir.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Boyutlu çizim</field><field id="photometricdata">Fotometrik bilgi</field><field id="month_1">Ocak</field><field id="month_2">Şubat</field><field id="month_3">Mart</field><field id="month_4">Nisan</field><field id="month_5">Mayıs</field><field id="month_6">Haziran</field><field id="month_7">Temmuz</field><field id="month_8">Ağustos</field><field id="month_9">Eylül</field><field id="month_10">Ekim</field><field id="month_11">Kasım</field><field id="month_12">Aralık</field><field id="benefits">Faydaları</field><field id="features">Özellikler</field><field id="application">Uygulama</field><field id="specifications">şartlar</field><field id="relatedproducts">İlgili ürünler</field><field id="accessories">aksesuarlar</field><field id="spectralpowerdistribution">Spektral Güç Dağılımı</field><field id="performancediagram">Performans diyagramı</field><field id="crvdiagram">CRV Diyagramı</field><field id="comparetable">Karşılaştırmak tablo</field><field id="productdetails">ÜRÜN BİLGİLERİ</field><field id="warningssafety">Güvenlik ve uyarılar</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_no_NO.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>no_NO</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">data kan endres</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Alle rettigheter forbeholdt.<br/>
<br/>
Spesifikasjonene kan endres uten varsel. Varemerkene eies av Koninklijke Philips Electronics N.V. eller deres respektive eiere.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Målskisse</field><field id="photometricdata">Fotometriske data</field><field id="month_1">Januar</field><field id="month_2">Februar</field><field id="month_3">Mars</field><field id="month_4">April</field><field id="month_5">Mai</field><field id="month_6">Juni</field><field id="month_7">Juli</field><field id="month_8">August</field><field id="month_9">Oktober</field><field id="month_10">September</field><field id="month_11">November</field><field id="month_12">Desember</field><field id="benefits">Fordeler</field><field id="features">Funksjoner</field><field id="application">Søknad</field><field id="specifications">spesifikasjoner</field><field id="relatedproducts">Andre prosjekter</field><field id="accessories">Tilbehør</field><field id="spectralpowerdistribution">Spectral kraftdistribusjon</field><field id="performancediagram">Ytelse diagram</field><field id="crvdiagram">CRV diagram</field><field id="comparetable">Sammenlign tabellen</field><field id="productdetails">Produkt detaljer</field><field id="warningssafety">Warnings and safety</field></fields></static_text>
