=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_file_locale.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="static_text">
		<xs:complexType>
			<xs:sequence>
				<xs:any namespace="http://www.relate4u.com/xsl/documentation" processContents="skip"/>
				<xs:element ref="fields"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="field"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType mixed="true">
			<xs:choice>
				<xs:group maxOccurs="unbounded" minOccurs="0" ref="markup"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:NCName" use="required"/>
		</xs:complexType>
	</xs:element>
	<!-- inline markup elements -->
	<xs:group name="markup">
		<xs:choice>
			<xs:element ref="b"/>
			<xs:element ref="br"/>
		</xs:choice>
	</xs:group>
	<xs:element name="br"/>
	<xs:element name="b">
		<xs:complexType mixed="true"/>
	</xs:element>
</xs:schema>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_it_IT.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>it_IT</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Dati soggetti a modifiche</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Tutti i diritti riservati.<br/>
<br/>
Le specifiche sono soggette a modifica senza previa notifica. Trademarks are the property of Koninklijke Philips Electronics N.V. or their respective owners.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Disegno tecnico</field><field id="photometricdata">Fotometrie</field><field id="month_1">Gennaio</field><field id="month_2">Febbraio</field><field id="month_3">Marzo</field><field id="month_4">Aprile</field><field id="month_5">Maggio</field><field id="month_6">Giugno</field><field id="month_7">Luglio</field><field id="month_8">Agosto</field><field id="month_9">Settembre</field><field id="month_10">Ottobre</field><field id="month_11">Novembre</field><field id="month_12">Dicembre</field><field id="benefits">Vantaggi</field><field id="features">Caratteristiche</field><field id="application">Applicazione</field><field id="specifications">Specifiche </field><field id="relatedproducts">Prodotti collegati</field><field id="accessories">Accessori</field><field id="spectralpowerdistribution">Distribuzione spettrale della luce</field><field id="performancediagram">Diagramma prestazionale</field><field id="crvdiagram">Diagramma CRV</field><field id="comparetable">Tavolo Confronto</field><field id="productdetails">Dati del prodotto</field><field id="warningssafety">Warnings and safety</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_da_DK.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>da_DK</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">registrerede til at ændre</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Alle rettigheder reserved.<br/>
<br/>
Specifications kan ændres uden varsel. Varemærker tilhører Koninklijke Philips Electronics NV eller deres respektive ejere.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Målskitse</field><field id="photometricdata">Fotometriske data</field><field id="month_1">januar</field><field id="month_2">februar</field><field id="month_3">marts</field><field id="month_4">april</field><field id="month_5">maj</field><field id="month_6">juni</field><field id="month_7">juli</field><field id="month_8">august</field><field id="month_9">september</field><field id="month_10">oktober</field><field id="month_11">november</field><field id="month_12">december</field><field id="benefits">Fordele</field><field id="features">Funktioner</field><field id="application">Ansøgning</field><field id="specifications">Specifikationer</field><field id="relatedproducts">Relaterede produkter</field><field id="accessories">Tilbehør</field><field id="spectralpowerdistribution">Spektral effekttæthed distribution</field><field id="performancediagram">Præstation diagram</field><field id="crvdiagram">CRV diagram</field><field id="comparetable">Sammenlign tabel</field><field id="productdetails">Oplysninger om produktet</field><field id="warningssafety">Advarsler og sikkerhed</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_hu_HU.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>hu_HU</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">az adatok változhatnak</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Minden jog fenntartva.<br/>
<br/>
A műszaki adatok előzetes figyelmeztetés nélkül változhatnak. Minden védjegy a Koninklijke Philips Electronics N.V. céget, vagy az illető jogtulajdonost illeti.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Méretezett rajza</field><field id="photometricdata">Fotometriai adatok</field><field id="month_1">Január</field><field id="month_2">Február</field><field id="month_3">Március</field><field id="month_4">Április</field><field id="month_5">Május</field><field id="month_6">Június</field><field id="month_7">Július</field><field id="month_8">Augusztus</field><field id="month_9">Szeptember</field><field id="month_10">Október</field><field id="month_11">November</field><field id="month_12">December</field><field id="benefits">Előnyök</field><field id="features">Szolgáltatások</field><field id="application">Alkalmazás</field><field id="specifications">termékjellemzők</field><field id="relatedproducts">Kapcsolódó termékek</field><field id="accessories">Tartozékok</field><field id="spectralpowerdistribution">Spektrális teljesítmény eloszlása</field><field id="performancediagram">Teljesítmény diagram</field><field id="crvdiagram">CRV diagram</field><field id="comparetable">Hasonlítsa össze a tábla</field><field id="productdetails">Termék részletei</field><field id="warningssafety">Figyelmeztetések és biztonság</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_ro_RO.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>ro_RO</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Informatie ce poate fi modificată</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Toate drepturile rezervate.<br/>
<br/>
Specificaţiile pot fi schimbate fără notificare. Informaţiile constituie proprietatea Koninklijke Philips Electronics N.V. <br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Cote</field><field id="photometricdata">Date fotometrice</field><field id="month_1">Ianuarie</field><field id="month_2">Februarie</field><field id="month_3">Martie</field><field id="month_4">Aprilie</field><field id="month_5">Mai</field><field id="month_6">Iunie</field><field id="month_7">Iulie</field><field id="month_8">August</field><field id="month_9">Septembrie</field><field id="month_10">Octombrie</field><field id="month_11">Noiembrie</field><field id="month_12">Decembrie</field><field id="benefits">Beneficii</field><field id="features">Caracteristici</field><field id="application">Cerere</field><field id="specifications">Specificaţii</field><field id="relatedproducts">Produse similare</field><field id="accessories">Accesorii</field><field id="spectralpowerdistribution">Distribuţia puterii spectrale</field><field id="performancediagram">Diagrama de performanţă</field><field id="crvdiagram">Diagrama CRV</field><field id="comparetable">Compara tabel</field><field id="productdetails">Detalii produs</field><field id="warningssafety">Warnings and safety</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_ko_KR.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>ko_KR</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">변경될 수 있는 데이터</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">All rights reserved.<br/>
<br/>
사양은 예고 없이 변경될 수 있습니다. 상표는 Koninklijke Philips Electronics N.V. 또는 해당 소유자의 자산입니다.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">치수 도면</field><field id="photometricdata">광도계의 데이터</field><field id="month_1">1월</field><field id="month_2">2월</field><field id="month_3">3월</field><field id="month_4">4월</field><field id="month_5">5월</field><field id="month_6">6월</field><field id="month_7">7월</field><field id="month_8">8월</field><field id="month_9">9월</field><field id="month_10">10월</field><field id="month_11">11월</field><field id="month_12">12월</field><field id="benefits">장점</field><field id="features">특징</field><field id="application">신청</field><field id="specifications">사양</field><field id="relatedproducts">관련 제품</field><field id="accessories">액세서리</field><field id="spectralpowerdistribution">스펙트럼 전력 분배</field><field id="performancediagram">성능 다이어그램</field><field id="crvdiagram">CRV 다이어그램</field><field id="comparetable">비교 테이블</field><field id="productdetails">제품 세부 사항</field><field id="warningssafety">안전 및 주의사항</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_sk_SK.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>sk_SK</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Údaje podliehajú zmenám</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Všetky práva vyhradené.<br/>
<br/>
Špecifikácia podlieha zmenám bez predchádzajúceho upozornenia. Obchodné značky sú majetkom Koninklijke Philips Electronics N.V. alebo jej príslušných majiteľiv..<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Rozmerový obrázok</field><field id="photometricdata">Fotometrické údaje</field><field id="month_1">Január</field><field id="month_2">Február</field><field id="month_3">Marec</field><field id="month_4">Apríl</field><field id="month_5">Máj</field><field id="month_6">Jún</field><field id="month_7">Júl</field><field id="month_8">August</field><field id="month_9">September</field><field id="month_10">Október</field><field id="month_11">November</field><field id="month_12">December</field><field id="benefits">Výhody</field><field id="features">Vlastnosti</field><field id="application">Aplikácie</field><field id="specifications">Špecifikácia</field><field id="relatedproducts">Príbuzné produkty</field><field id="accessories">Príslušenstvo</field><field id="spectralpowerdistribution">Spektrálne rozloženie</field><field id="performancediagram">Krivka účinnosti</field><field id="crvdiagram">CRV krivka</field><field id="comparetable">Porovnať tabuľka</field><field id="productdetails">Podrobnosti o produkte</field><field id="warningssafety">Varovanie a ochrana</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_es_ES.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>es_ES</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Datos sujetos a cambios</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Todos los derechos reservados.<br/>
<br/>
Las especificaciones están sujetas a cambios sin previo aviso. Las marcas registradas son propiedad de Koninklijke Philips Electronics N.V. o de sus respectivos propietarios.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Plano de dimensiones</field><field id="photometricdata">Datos fotométricos</field><field id="month_1">Enero</field><field id="month_2">Febrero</field><field id="month_3">Marzo</field><field id="month_4">Abril</field><field id="month_5">Mayo</field><field id="month_6">Junio</field><field id="month_7">Julio</field><field id="month_8">Agosto</field><field id="month_9">Septiembre</field><field id="month_10">Octubre</field><field id="month_11">Noviembre</field><field id="month_12">Diciembre</field><field id="benefits">Beneficios</field><field id="features">Características</field><field id="application">Aplicaciones</field><field id="specifications">Especificaciones</field><field id="relatedproducts">Productos relacionados</field><field id="accessories">Accesorios</field><field id="spectralpowerdistribution">Distribución de potencia espectral</field><field id="performancediagram">Diagrama de rendimiento</field><field id="crvdiagram">Diagrama de CRV</field><field id="comparetable">Tabla comparativa</field><field id="productdetails">Detalles del producto</field><field id="warningssafety">Advertencias y seguridad</field></fields></static_text>

=== bvhest/Pikachu_Analysis/webapp.b2c/pipes/LeafletRendering/Assets/Static text/static_text_FMT_pt_PT.xml
<?xml version="1.0" encoding="UTF-8"?><static_text xmlns:gmr="http://www.gnome.org/gnumeric/v7" xmlns:doc="http://www.relate4u.com/xsl/documentation" xmlns:ws="http://apache.org/cocoon/source/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="static_text_file_locale.xsd"><doc:asset><doc:author><doc:name>Pikachu</doc:name><doc:company>Philips, Eindhoven</doc:company><doc:email>pikachu.b2b.support@philips.com</doc:email></doc:author><doc:description>
                  Static text file for Philips Lighting product brochures XSL-FO stylesheet.
                  This file contains translated static text fields which are not available in the product XML files.
                  Last updated: 2011-03-01T11:02:32.338+01:00</doc:description><doc:language>pt_PT</doc:language><doc:document-type>FMT</doc:document-type></doc:asset><fields><field id="date_change">Dados sujeitos a alteração</field><field id="copyright_royal">Koninklijke Philips Electronics N.V.</field><field id="copyright_text">Todos os direitos reservados<br/>
<br/>
As especificações estão sujeitas a alterações sem aviso prévio. As marcas comerciais são propriedade de Koninklijke Philips Electronics NV ou de seus respectivos proprietários.<br/>
<br/>
<b>www.philips.com/lighting</b></field><field id="dimensionaldrawing">Desenho dimensional</field><field id="photometricdata">Dados fotométricos</field><field id="month_1">Janeiro</field><field id="month_2">Fevereiro</field><field id="month_3">Março</field><field id="month_4">Abril</field><field id="month_5">Maio</field><field id="month_6">Junho</field><field id="month_7">Julho</field><field id="month_8">Agosto</field><field id="month_9">Setembro</field><field id="month_10">Outubro</field><field id="month_11">Novembro</field><field id="month_12">Dezembro</field><field id="benefits">Benefícios</field><field id="features">Características</field><field id="application">Aplicação</field><field id="specifications">Especificações</field><field id="relatedproducts">Produtos relacionados</field><field id="accessories">Acessórios</field><field id="spectralpowerdistribution">Distribuição de energia espectral</field><field id="performancediagram">Diagrama de desempenho</field><field id="crvdiagram">Diagrama CRV</field><field id="comparetable">Compare preços de tabela</field><field id="productdetails">Detalhes do produto</field><field id="warningssafety">Avisos e Segurança</field></fields></static_text>
